<?php
/**
 * Shared installer runner for Hostinger-safe setup.
 * Called from index.php (preferred) or process.php.
 */

function news_portal_run_install(array $post)
{
    $db_host = trim($post['db_host'] ?? 'localhost');
    $db_name = trim($post['db_name'] ?? '');
    $db_user = trim($post['db_user'] ?? '');
    $db_pass = (string)($post['db_pass'] ?? '');
    $db_collation = $post['db_collation'] ?? 'utf8mb4_unicode_ci';
    $allowed_collations = ['utf8mb4_unicode_ci', 'utf8mb4_general_ci', 'utf8mb4_0900_ai_ci'];
    if (!in_array($db_collation, $allowed_collations, true)) {
        $db_collation = 'utf8mb4_unicode_ci';
    }

    $site_name = trim($post['site_name'] ?? '');
    if ($site_name === '') {
        $site_name = 'News Portal';
    }

    $admin_name = trim($post['admin_name'] ?? '');
    $admin_email = trim($post['admin_email'] ?? '');
    $admin_pass = (string)($post['admin_pass'] ?? '');

    if ($db_name === '' || $db_user === '' || $admin_name === '' || $admin_email === '' || $admin_pass === '') {
        throw new Exception('Please fill all required fields.');
    }
    if (!filter_var($admin_email, FILTER_VALIDATE_EMAIL)) {
        throw new Exception('Admin email is invalid.');
    }
    if (strlen($admin_pass) < 6) {
        throw new Exception('Admin password must be at least 6 characters.');
    }

    $schema_file = __DIR__ . '/schema.sql';
    if (!is_file($schema_file)) {
        throw new Exception('schema.sql is missing in the install folder.');
    }

    $dsn = "mysql:host={$db_host};dbname={$db_name};charset=utf8mb4";
    $pdo = new PDO($dsn, $db_user, $db_pass, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    ]);

    $sql_content = file_get_contents($schema_file);
    $sql_content = str_replace('[[COLLATION]]', $db_collation, $sql_content);

    // Run one statement at a time (Hostinger often blocks multi-query exec)
    $statements = preg_split('/;\s*[\r\n]+/', $sql_content);
    foreach ($statements as $statement) {
        $statement = trim($statement);
        if ($statement === '' || strpos($statement, '--') === 0) {
            continue;
        }
        $pdo->exec($statement);
    }

    $hashed_pass = password_hash($admin_pass, PASSWORD_BCRYPT);
    $stmt = $pdo->prepare("INSERT INTO users (name, email, password, role, status) VALUES (?, ?, ?, 'admin', 1)");
    $stmt->execute([$admin_name, $admin_email, $hashed_pass]);

    $stmt = $pdo->prepare("UPDATE settings SET setting_value = ? WHERE setting_key = 'site_name'");
    $stmt->execute([$site_name]);

    $protocol = (
        (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ||
        (($_SERVER['HTTP_X_FORWARDED_PROTO'] ?? '') === 'https')
    ) ? 'https' : 'http';
    $host = $_SERVER['HTTP_HOST'] ?? 'localhost';
    $request_path = parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH);
    $request_path = str_replace(['\\', '//'], '/', (string)$request_path);
    $current_dir = rtrim(preg_replace('#/install/(index\\.php|process\\.php)?$#', '', $request_path), '/');
    $rewrite_base = $current_dir === '' ? '/' : $current_dir . '/';
    $base_url = rtrim($protocol . '://' . $host . $current_dir, '/');
    $uri_prefix = $current_dir;
    $error_doc = $current_dir === '' ? '/404.php' : $current_dir . '/404.php';

    $db_config_content = "<?php\n"
        . "\$host = " . var_export($db_host, true) . ";\n"
        . "\$db_name = " . var_export($db_name, true) . ";\n"
        . "\$username = " . var_export($db_user, true) . ";\n"
        . "\$password = " . var_export($db_pass, true) . ";\n\n"
        . "try {\n"
        . "    \$conn = new PDO(\"mysql:host=\$host;dbname=\$db_name;charset=utf8mb4\", \$username, \$password);\n"
        . "    \$conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);\n"
        . "    \$conn->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);\n"
        . "    \$conn->exec(\"SET time_zone = '+05:30'\");\n"
        . "} catch (PDOException \$e) {\n"
        . "    error_log('Database Connection Error: ' . \$e->getMessage());\n"
        . "    die('Database connection failed.');\n"
        . "}\n";

    $const_file_content = "<?php\n"
        . "// Auto-generated by Installation Wizard\n"
        . "date_default_timezone_set('Asia/Kolkata');\n\n"
        . "define('SITE_NAME', " . var_export($site_name, true) . ");\n"
        . "define('BASE_URL', " . var_export($base_url, true) . ");\n"
        . "define('UPLOAD_PATH', __DIR__ . '/../uploads/');\n\n"
        . "if (session_status() === PHP_SESSION_NONE) {\n"
        . "    session_start();\n"
        . "}\n";

    $htaccess_content = "RewriteEngine On\n"
        . "RewriteBase {$rewrite_base}\n\n"
        . "ErrorDocument 404 {$error_doc}\n\n"
        . "RewriteCond %{REQUEST_URI} ^{$uri_prefix}/admin/ [NC,OR]\n"
        . "RewriteCond %{REQUEST_URI} ^{$uri_prefix}/handlers/ [NC,OR]\n"
        . "RewriteCond %{REQUEST_URI} ^{$uri_prefix}/install/ [NC]\n"
        . "RewriteRule .* - [L]\n\n"
        . "RewriteCond %{THE_REQUEST} ^[A-Z]{3,}\\s([^.]+)\\.php [NC]\n"
        . "RewriteRule ^ %1 [R=301,L]\n\n"
        . "RewriteRule ^article/([^/]+)/?$ article.php?slug=\$1 [L,QSA]\n"
        . "RewriteRule ^category/([^/]+)/?$ category.php?slug=\$1 [L,QSA]\n"
        . "RewriteRule ^tag/([^/]+)/?$ tag.php?slug=\$1 [L,QSA]\n"
        . "RewriteRule ^author/([^/]+)/?$ author.php?slug=\$1 [L,QSA]\n"
        . "RewriteRule ^search/([^/]+)/?$ search.php?q=\$1 [L,QSA]\n"
        . "RewriteRule ^rss/?$ rss.php [L,QSA]\n"
        . "RewriteRule ^sitemap\\.xml$ sitemap.php [L,QSA]\n"
        . "RewriteRule ^sitemap/?$ sitemap.php [L,QSA]\n\n"
        . "RewriteCond %{REQUEST_FILENAME} !-d\n"
        . "RewriteCond %{REQUEST_FILENAME}\\.php -f\n"
        . "RewriteRule ^(.*)\$ \$1.php [L]\n\n"
        . "RewriteCond %{REQUEST_FILENAME} !-f\n"
        . "RewriteCond %{REQUEST_FILENAME} !-d\n"
        . "RewriteRule ^ 404.php [L]\n";

    $writes = [
        __DIR__ . '/../config/database.php' => $db_config_content,
        __DIR__ . '/../config/constants.php' => $const_file_content,
        __DIR__ . '/../.htaccess' => $htaccess_content,
        __DIR__ . '/../config/install.lock' => date('Y-m-d H:i:s') . ' - Installed by ' . $admin_email,
    ];

    foreach ($writes as $path => $content) {
        if (@file_put_contents($path, $content) === false) {
            throw new Exception('Could not write file: ' . basename(dirname($path)) . '/' . basename($path) . '. Set permissions to 755.');
        }
    }

    return true;
}

function news_portal_install_error_html($message)
{
    return "<div style='font-family:sans-serif;padding:40px;max-width:640px;margin:40px auto;border:1px solid #fecaca;background:#fef2f2;border-radius:16px;'>"
        . "<h2 style='color:#b91c1c;margin-top:0;'>Installation Error</h2>"
        . "<p style='color:#7f1d1d;line-height:1.5;'>" . htmlspecialchars((string)$message) . "</p>"
        . "<p style='color:#991b1b;font-size:14px;'>Hostinger tip: DB Host = <strong>localhost</strong>. Use the exact database name/user/password from hPanel → Databases.</p>"
        . "<a href='index.php' style='display:inline-block;margin-top:12px;background:#4f46e5;color:#fff;text-decoration:none;padding:10px 16px;border-radius:10px;'>Back to installer</a>"
        . "</div>";
}
