<?php
session_start();

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    header("Location: index.php");
    exit();
}

$db_host = trim($_POST['db_host']);
$db_name = trim($_POST['db_name']);
$db_user = trim($_POST['db_user']);
$db_pass = trim($_POST['db_pass']);
$db_collation = $_POST['db_collation'];

$site_name = trim($_POST['site_name']);
if (empty($site_name)) $site_name = "News Portal";

$admin_name = trim($_POST['admin_name']);
$admin_email = trim($_POST['admin_email']);
$admin_pass = $_POST['admin_pass'];

try {
    $dsn = "mysql:host=$db_host;dbname=$db_name;charset=utf8mb4";
    $pdo = new PDO($dsn, $db_user, $db_pass);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

    if (!file_exists('schema.sql')) {
        die("Error: schema.sql file missing in install folder.");
    }

    $sql_content = file_get_contents('schema.sql');
    $sql_content = str_replace('[[COLLATION]]', $db_collation, $sql_content);

    $pdo->exec($sql_content);

    $hashed_pass = password_hash($admin_pass, PASSWORD_BCRYPT);
    $stmt = $pdo->prepare("INSERT INTO users (name, email, password, role, status) VALUES (?, ?, ?, 'admin', 1)");
    $stmt->execute([$admin_name, $admin_email, $hashed_pass]);

    $stmt = $pdo->prepare("UPDATE settings SET setting_value = ? WHERE setting_key = 'site_name'");
    $stmt->execute([$site_name]);

    $db_config_content = "<?php
\$host = '$db_host';
\$db_name = '$db_name';
\$username = '$db_user';
\$password = '$db_pass';

try {
    \$conn = new PDO(\"mysql:host=\$host;dbname=\$db_name;charset=utf8mb4\", \$username, \$password);
    \$conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    \$conn->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
    
    // Auto-set Indian Timezone for DB
    \$conn->exec(\"SET time_zone = '+05:30'\");

} catch(PDOException \$e) {
    error_log(\"Database Connection Error: \" . \$e->getMessage());
    die(\"Database connection failed.\");
}
?>";
    file_put_contents('../config/database.php', $db_config_content);

    $protocol = (
        (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ||
        (($_SERVER['HTTP_X_FORWARDED_PROTO'] ?? '') === 'https')
    ) ? "https" : "http";
    $host = $_SERVER['HTTP_HOST'];
    $request_path = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
    $current_dir = rtrim(str_replace('/install/process.php', '', $request_path), '/');
    $rewrite_base = $current_dir === '' ? '/' : $current_dir . '/';
    $base_url = rtrim($protocol . "://" . $host . $current_dir, '/');
    $safe_site_name = addslashes($site_name);

    $const_file_content = "<?php
// Auto-generated by Installation Wizard
date_default_timezone_set('Asia/Kolkata');

define('SITE_NAME', '$safe_site_name');
define('BASE_URL', '$base_url');
define('UPLOAD_PATH', __DIR__ . '/../uploads/');

if (session_status() === PHP_SESSION_NONE) {
    session_start();
}
?>";
    file_put_contents('../config/constants.php', $const_file_content);
    $htaccess_content = "RewriteEngine On
RewriteBase $rewrite_base

# Custom 404
ErrorDocument 404 $current_dir/404.php

# Exclude Admin Folder
RewriteCond %{REQUEST_URI} ^" . $current_dir . "/admin/ [NC]
RewriteRule .* - [L]

# Exclude public handlers (keep POST body)
RewriteCond %{REQUEST_URI} ^" . $current_dir . "/handlers/ [NC]
RewriteRule .* - [L]

# Hide .php extension
RewriteCond %{THE_REQUEST} ^[A-Z]{3,}\\s([^.]+)\\.php [NC]
RewriteRule ^ %1 [R=301,L]

# Rewrite Rules for News
RewriteRule ^article/([^/]+)/?$ article.php?slug=\$1 [L,QSA]
RewriteRule ^category/([^/]+)/?$ category.php?slug=\$1 [L,QSA]
RewriteRule ^tag/([^/]+)/?$ tag.php?slug=\$1 [L,QSA]
RewriteRule ^author/([^/]+)/?$ author.php?slug=\$1 [L,QSA]
RewriteRule ^search/([^/]+)/?$ search.php?q=\$1 [L,QSA]
RewriteRule ^rss/?$ rss.php [L,QSA]
RewriteRule ^sitemap\\.xml$ sitemap.php [L,QSA]
RewriteRule ^sitemap/?$ sitemap.php [L,QSA]

# General .php hiding
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME}\\.php -f
RewriteRule ^(.*)\$ \$1.php [L]

# Fallback unknown paths to 404
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ 404.php [L]";

    file_put_contents('../.htaccess', $htaccess_content);

    file_put_contents('../config/install.lock', date('Y-m-d H:i:s') . " - Installed by $admin_email");

    header("Location: index.php?finish=success");
    exit();
} catch (PDOException $e) {
    die("<div style='font-family:sans-serif; padding:50px; text-align:center;'>
            <h2 style='color:red;'>Installation Error</h2>
            <p>Could not connect to the database. Please check your credentials.</p>
            <p style='color:#666;'>Details: " . $e->getMessage() . "</p>
            <a href='index.php' style='color:blue;'>Go Back and Retry</a>
         </div>");
} catch (Exception $e) {
    die("System Error: " . $e->getMessage());
}
